'📚 documentation':
  - any: ['docs/**', '!docs/**/package.json']

'🌀 cli':
  - any: ['cli/**', '!cli/**/package.json']

'apps':
  - any: ['apps/**', '!apps/**/package.json']

'@coursebuilder/ui':
  - any: [ 'packages/ui/**', '!packages/ui/package.json' ]


